version: "3.7"
services:
    php:
        build:
            context: .
        image: php
        container_name: hash_app
        ports:
            - "8000:8000"
        volumes:
            - ".:/var/www/html/"
        command: php -S 0.0.0.0:8000 -t public/
